### ISSUE TITLE
Can't seem to run this on ARM / Raspberry Pi 3

### ISSUE THREAD

**Issue by Fossil01** [pokusew/nfc-pcsc#107]
Hi,

My app runs fine on Mac or Linux x86 but I am trying to get it to work on a Raspberry Pi. I am using the same Node version as on my Mac (v14.15.0) , installed pcscd, libpcsclite-dev, libpcsclite1 (all version 1.8.26) and started pcscd. But when I run it I get this error:

```
/home/USERNAME/git/node_modules/@pokusew/pcsclite/lib/pcsclite.js:46
	const p = new PCSCLite();
	          ^

Error: SCardEstablishContext error: RPC transport error.(0x80100013)
    at module.exports (/home/USERNAME/git/node_modules/@pokusew/pcsclite/lib/pcsclite.js:46:12)
    at new NFC (/home/USERNAME/git/node_modules/nfc-pcsc/dist/NFC.js:28:39)
    at Object.<anonymous> (/home/USERNAME/git/main.js:75:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by Fossil01** [comment]
I was using a snap package to install the correct node version, which turns out is not fully supported in my specific case. After installing the NodeSource repo and re-installing Node everything worked.
