### ISSUE TITLE
Ultralight EV1 password authentication

### ISSUE THREAD

**Issue by RomanBobko** [pokusew/nfc-pcsc#32]
Hello,
Thanks a lot for this library!
I'm try write data to Mifare Ultralight EV1 card with password.
Before write, i'm try send pseudo-APDU command PWD_AUTH (0x1B) but response empty buffer and data write error.
How can i send authenticate command?
Pleas help.

Here is my code:
```
const { NFC } = require('nfc-pcsc');
const nfc = new NFC();

nfc.on('reader', reader => {

    console.log(`${ reader.reader.name } device attached`);

    reader.on('card', async card => {

        try {
            // APDU CMD: Update Binary Block
            const packet = new Buffer([
                0xFF, // Class				
                0x00,
                0x00,
                0x00,
                0x05, //Length
                0x1B, //PWD_AUTH
                0x11, //my pass
                0x22, //my pass
                0x33, //my pass
                0x44 //my pass
            ]);
            var pwdResponse = await reader.transmit(packet, 2);  
            console.log('pwd response', pwdResponse);
        } catch (err) {
            console.log('error pwd_auth');
        }
        
        try {
            const data = Buffer.allocUnsafe(12);
            data.fill(0);
            const text = (new Date()).toTimeString();
            data.write(text);      
            await reader.write(4, data); 

            console.log('data written');
           
        } catch (err) {
            console.error('error when writing data', err);
        }       
    });
});
```

```
ACS ACR122 0 device attached
pwd response <Buffer >
error when writing data { WriteError: Write operation failed: Status code: 0x6300
    at C:\Users\admin\Documents\acr122u\node_modules\nfc-pcsc\dist\Reader.js:579:11
    at Generator.next (<anonymous>)
    at step (C:\Users\admin\Documents\acr122u\node_modules\nfc-pcsc\dist\Reader.js:18:191)
    at C:\Users\admin\Documents\acr122u\node_modules\nfc-pcsc\dist\Reader.js:18:361
    at <anonymous> name: 'WriteError', code: 'operation_failed' }
```

**Comment by RomanBobko** [comment]
I finded solution my problem.
In packet need insert 2 bytes 0xD4, 0x42, and Length change to 0x07
In method response second paramether change to 7

            // APDU CMD: Update Binary Block
            const packet = new Buffer([
                0xFF, // Class				
                0x00,
                0x00,
                0x00,
                0x07, //Length
                0xD4, // inserted
                0x42, // inserted
                0x1B, //PWD_AUTH
                0x11, //my pass
                0x22, //my pass
                0x33, //my pass
                0x44 //my pass
            ]);
            var pwdResponse = await reader.transmit(packet, 7);  // 7 response size
            console.log('pwd response', pwdResponse);
