### ISSUE TITLE
WriteError: Write operation failed: Status code: 0x6300

### ISSUE THREAD

**Issue by h4ng3r** [pokusew/nfc-pcsc#45]
I'm trying to write in a Mifare 1k card empty with all keys to FFFFFFFFFFFF, I followed the examples and read some similar questions but I always end up with the same error.

My testing code is:

```
const { NFC } = require('nfc-pcsc');
const nfc = new NFC();
const KEY_TYPE_A = 0x60
const KEY_TYPE_B = 0x61
nfc.on('reader', (reader) => {
	reader.on('card', async (card) => {
		try {
			const data = Buffer.allocUnsafe(16);
			data.fill(0);
			const randomNumber = Math.round(Math.random() * 1000);
			data.writeInt16BE(randomNumber);

			await reader.authenticate(4, KEY_TYPE_A, 'ffffffffffff')
			await reader.authenticate(5, KEY_TYPE_A, 'ffffffffffff')
			await reader.authenticate(6, KEY_TYPE_A, 'ffffffffffff')
			await reader.write(4, data, 16);
		} catch (err) {
			console.error(err)
		}
	})
})

```

This is the error I'm getting:
```
{ WriteError: Write operation failed: Status code: 0x6300
    at /home/XXXXXX/node_modules/nfc-pcsc/dist/Reader.js:579:11
    at Generator.next (<anonymous>)
    at step (/home/XXXXXX/node_modules/nfc-pcsc/dist/Reader.js:18:191)
    at /home/XXXXXX/node_modules/nfc-pcsc/dist/Reader.js:18:361
    at <anonymous> name: 'WriteError', code: 'operation_failed' }
```

I'm using an empty card with the following content (with gen1 backdoor):
```
0102030404080400000000000000beaf
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000000
ffffffffffff08778f00ffffffffffff
00000000000000000000000000000000
```

Thanks

**Comment by h4ng3r** [comment]
Working with B key, sorry.
