### ISSUE TITLE
Error on Win 10 whiile CONNECT_MODE_DIRECT 

### ISSUE THREAD

**Issue by IrakliTabagari** [pokusew/nfc-pcsc#66]
Hi,
Any progress connecting directly on Win 10?

```
try {
		await reader.connect(CONNECT_MODE_DIRECT);
		await reader.setBuzzerOutput(false);
		await reader.disconnect();
	} catch (err) {
		console.log(err);
	}
```

{ ControlError: An error occurred while transmitting control.
at reader.control (...\node_modules\nfc-pcsc\dist\Reader.js:260:25)
at ...\node_modules@pokusew\pcsclite\lib\pcsclite.js:170:11
name: 'ControlError',
code: 'failure',
previous: Error: **SCardControl** error: Incorrect function.
(0x00000001) }

**Comment by Franx0** [comment]
@IrakliTabagari it looks like your are trying to execute control method before connect your reader, could you show us your block code to see if you are attempting to execute control before connect?
